### ISSUE TITLE
Unable to recieve messages

### ISSUE THREAD

**Issue by jefking** [jefking/King.Service.ServiceBus#10]
```
King.Service.ServiceBus.Demo Error: 0 : Failed to start King.Service.ServiceBus.Demo.Tasks.CompanyDequeuer: System.InvalidOperationException: A message handler has already been registered.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnMessageHandler(MessageHandlerOptions registerHandlerOptions, Func`3 callback) in C:\source\azure-service-bus-dotnet\src\Microsoft.Azure.ServiceBus\Core\MessageReceiver.cs:line 1273
   at King.Service.ServiceBus.Wrappers.BusQueueClient.OnMessage(Func`3 callback, MessageHandlerOptions options) in /home/jbdking/github/King.Service.ServiceBus/King.Service.ServiceBus/Wrappers/BusQueueClient.cs:line 95
   at King.Service.ServiceBus.BusEvents`1.Run() in /home/jbdking/github/King.Service.ServiceBus/King.Service.ServiceBus/BusEvents.cs:line 88
   at King.Service.InitializeTask.Start()
   at King.Service.RoleTaskManager`1.<>c__DisplayClass10_0.<Run>b__0(Object index)
```

**Comment by jefking** [comment]
this is released.
